-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS USERS(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    NAME TEXT
);
COMMENT ON TABLE USERS IS 'Пользователи.';

CREATE TABLE IF NOT EXISTS TASKS(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    OPENED BIGINT NOT NULL,
    CLOSED BIGINT NOT NULL,
    AUTHOR_ID INTEGER, 
    ASSIGNED_ID INTEGER, 
    TITLE TEXT,
    CONTENT TEXT
);
COMMENT ON TABLE TASKS IS 'Задачи пользователей.';

CREATE TABLE IF NOT EXISTS LABELS(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    NAME TEXT
);
COMMENT ON TABLE LABELS IS 'Метки.';

CREATE TABLE IF NOT EXISTS TASKS_LABELS(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    TASK_ID INTEGER NOT NULL,
    LABEL_ID  INTEGER NOT NULL
);

ALTER TABLE TASKS ADD CONSTRAINT FK_USERS_TASKS_ASSIGNED
FOREIGN KEY (AUTHOR_ID) REFERENCES USERS(ID) ON DELETE CASCADE;

ALTER TABLE TASKS ADD CONSTRAINT FK_USERS_TASKS_AUTHOR
FOREIGN KEY (ASSIGNED_ID) REFERENCES USERS(ID) ON DELETE CASCADE;


ALTER TABLE TASKS_LABELS ADD CONSTRAINT FK_TASKS_LABELS_TASK
FOREIGN KEY (TASK_ID) REFERENCES TASKS(ID) ON DELETE CASCADE;

ALTER TABLE TASKS_LABELS ADD CONSTRAINT FK_TASKS_LABELS_LABEL
FOREIGN KEY (LABEL_ID) REFERENCES LABELS(ID) ON DELETE CASCADE;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE TASKS_LABELS CASCADE;
DROP TABLE LABELS CASCADE;
DROP TABLE TASKS CASCADE;
DROP TABLE USERS CASCADE;
-- +goose StatementEnd
