-- +goose Up
-- +goose StatementBegin

INSERT INTO TASKS(ID,OPENED,CLOSED,AUTHOR_ID,ASSIGNED_ID,TITLE,CONTENT)
    VALUES  (1000, 0, 0, 100, 101, 'TEST1', 'TEST_1');

INSERT INTO TASKS(ID,OPENED,CLOSED,AUTHOR_ID,ASSIGNED_ID,TITLE,CONTENT)
    VALUES  (1001, 0, 0, 100, 101, 'TEST2', 'TEST_2');    

INSERT INTO TASKS(ID,OPENED,CLOSED,AUTHOR_ID,ASSIGNED_ID,TITLE,CONTENT)
    VALUES  (1002, 0, 0, 101, 100, 'TEST3', 'TEST_3');    

INSERT INTO TASKS(ID,OPENED,CLOSED,AUTHOR_ID,ASSIGNED_ID,TITLE,CONTENT)
    VALUES  (1003, 0, 0, 101, 100, 'TEST4', 'TEST_4');        


INSERT INTO TASKS_LABELS(ID, TASK_ID, LABEL_ID)
    VALUES  (100, 1000, 1);

INSERT INTO TASKS_LABELS(ID, TASK_ID, LABEL_ID)
    VALUES  (101, 1000, 2);    

INSERT INTO TASKS_LABELS(ID, TASK_ID, LABEL_ID)
    VALUES  (102, 1001, 1);

INSERT INTO TASKS_LABELS(ID, TASK_ID, LABEL_ID)
    VALUES  (103, 1001, 2);        

INSERT INTO TASKS_LABELS(ID, TASK_ID, LABEL_ID)
    VALUES  (104, 1002, 1);

INSERT INTO TASKS_LABELS(ID, TASK_ID, LABEL_ID)
    VALUES  (105, 1002, 2);    

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DELETE FROM TASKS;
DELETE FROM TASKS_LABELS;
-- +goose StatementEnd
